@startuml

class Shape
class Point
class Line
class Rectangle
class Square
class Ellipse
class Circle
class Triangle

Line --* Point
Shape --* Line
Rectangle --|> Shape
Square --|> Rectangle
Ellipse --|> Shape
Circle --|> Ellipse
Triangle --|> Shape

@enduml